#INCLUDE 'TOTVS.CH'
#INCLUDE 'APWEBSRV.CH'

WSSERVICE WSIMPRIME DESCRIPTION 'Imprime uma Mensagem'
	
	WSDATA cMensagem AS STRING
	WSDATA cImprime  AS STRING
	
	WSMETHOD IMPRIME DESCRIPTION 'Retorna a mensagem informada'
	
ENDWSSERVICE

WSMETHOD IMPRIME WSRECEIVE cMensagem WSSEND cImprime WSSERVICE WSIMPRIME
	
	::cImprime := ::cMensagem
	
RETURN .T.
