#INCLUDE 'TOTVS.CH'
#INCLUDE 'APWEBSRV.CH'

WSSERVICE WSOLAMUNDO DESCRIPTION 'WebService Olá Mundo'
	
	WSDATA cOlaMundo AS STRING
	
	WSMETHOD OLAMUNDO DESCRIPTION 'Retorna a mensagem Olá Mundo'
	
ENDWSSERVICE

WSMETHOD OLAMUNDO WSRECEIVE NULLPARAM WSSEND cOlaMundo WSSERVICE WSOLAMUNDO
	
	::cOlaMundo := 'Olá Mundo'
	
RETURN .T.
